### ISSUE TITLE
Containers should be full width by default

### ISSUE THREAD

**Issue by jordangehman** [aweber/aw-grid#23]
`aw-container` should have `width: 100%;` set so that it is full-width by default. Without it, containers will only be as wide as their contents, which is not expected functionality.

**Comment by davegomez** [comment]
That's the expected functionality for a grid system, the container shouldn't dictate any positioning or size, is just meant to hold the content.

**Comment by jordangehman** [comment]
@davegomez It is not expected functionality because the purpose of the container is to create a consistent space for the columns to fill. If the container is not consistently filling the width of its parent, layouts will be inconsistent. For example:

Without full-width, the container expands to the width of the content. This creates inconsistent layouts (of varying widths) when the container is being used to wrap page layouts:
![without full-width](https://user-images.githubusercontent.com/3800177/38041130-03886956-327f-11e8-89f4-f60e08879ed5.png)

With full-width, the container can be used to wrap page content with a consistent layout (full-width) regardless of the width of the content:
![with fill-width](https://user-images.githubusercontent.com/3800177/38041245-4236ab4a-327f-11e8-9ce7-2ab6140383dd.png)

The containers should, and already do, dictate size:
* `aw-container` does not have a `max-width`, but the expected behavior is that it will fill the width of its parent so that it can be used to wrap page content consistently regardless of content.
* `aw-container-fluid` has `max-width: 1140px;` with the expectation that `width: 100%;` is set as well.

**Comment by jordangehman** [comment]
The issue I was seeing was due to `display: flex;` being set on the `body`, which caused the `aw-container` child `div` to not behave correctly. The solution was to just wrap the container in a `div` so it would not be affected by flex inheritance.
